### ISSUE TITLE
OLT / VLAN

### ISSUE THREAD

**Issue by pcalves12** [mateusaires3/SAS---Sistema-de-Auxilio#1]
Uma guia geral na qual mostrará os seguintes dados que segue o anexo :

No qual vai orientar o suporte a corrigir a vlan dos clientes e para que os mesmo saibam a vlan correta. 

![captura de tela de 2015-09-09 09 19 47](https://cloud.githubusercontent.com/assets/14019630/9761569/e906ffd6-56d3-11e5-878f-77ed7fd46bc8.png)

**Comment by mateusaires3** [comment]
Primeira aba do sistema foi criado com sucesso, caso deseja alguma alteração informar !
![vlan](https://cloud.githubusercontent.com/assets/11586016/9797311/d1666526-57d0-11e5-9a80-7e4d33f6373c.png)

**Comment by mateusaires3** [comment]
Segunda-feira está pronto
