### ISSUE TITLE
Áreas / Autenticações 

### ISSUE THREAD

**Issue by pcalves12** [mateusaires3/SAS---Sistema-de-Auxilio#2]
Adicionar  a seguinte planilha no sistema :
https://docs.google.com/spreadsheets/d/1dVWkY0dPvnyIZKFzLm9ieKuaxZn2D13GqyW0Np96BBc/edit?pli=1#gid=1893197393

No qual seja da seguinte forma :
![captura de tela de 2015-09-09 09 27 30](https://cloud.githubusercontent.com/assets/14019630/9761749/04356d3c-56d5-11e5-8a75-074ba1e9b0e9.png)

**Comment by mateusaires3** [comment]
Segunda-feira está pronto
