### ISSUE TITLE
Descrição dos Planos

### ISSUE THREAD

**Issue by pcalves12** [mateusaires3/SAS---Sistema-de-Auxilio#4]
Segue um auxilio para os planos Residenciais :
![captura de tela de 2015-09-09 09 41 23](https://cloud.githubusercontent.com/assets/14019630/9762091/6abf6826-56d7-11e5-9979-0a714c1d33ab.png)
![captura de tela de 2015-09-09 09 44 25](https://cloud.githubusercontent.com/assets/14019630/9762093/6dbd1276-56d7-11e5-9df6-d5cd1ab08378.png)

**Comment by mateusaires3** [comment]
Segunda-feira está pronto
