### ISSUE TITLE
Sistema de Bloqueio Canopy

### ISSUE THREAD

**Issue by pcalves12** [mateusaires3/SAS---Sistema-de-Auxilio#8]
Segue a forma atual de bloquear o sistema canopy.

https://docs.google.com/spreadsheets/d/1Ssah6bHxbQg1nZ6Qo-gEGWmZHGJ7QCbESdEdThecjGY/edit#gid=233603558
![captura de tela de 2015-09-09 12 17 49](https://cloud.githubusercontent.com/assets/14019630/9765901/ccd8545e-56ec-11e5-9f70-9cfd7a9d8a9e.png)

Porém poderíamos fazer o uma forma mais pratica fazer tal trabalho. 
Estudar uma forma com vc.

**Comment by mateusaires3** [comment]
Segunda-feira está pronto
