### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by mateusaires3** [mateusaires3/SAS---Sistema-de-Auxilio#9]
![captura de tela de 2015-09-09 14 20 54](https://cloud.githubusercontent.com/assets/11586016/9769050/02539dda-56fe-11e5-8ab4-f421e290eae2.png)

Deseja fazer alguma alteração no layout? ou pode ser assim

**Comment by pcalves12** [comment]
Pode ser assim, ficou muito bom!
